/**:
  ros__parameters:
    video_device: "/dev/video0"      # 左目设备路径
    image_width: 640
    image_height: 240
    pixel_format: "mjpeg2rgb"             # 或 "mjpeg", "uyvy" 等
    camera_name: "stereo_camera"
    camera_frame_id: "stereo_link"
    io_method: "mmap"
    #camera_info_url: "file:///path/to/left_camera_info.yaml"
